const fs = require('fs');

const langs = ['fr', 'pt', 'it', 'de', 'ru'];

const authTranslations = {
  fr: {
    "login": "Connexion",
    "welcomeBack": "Heureux de vous revoir !",
    "email": "Email",
    "password": "Mot de passe",
    "signIn": "Se connecter",
    "creatingAccount": "Création du compte...",
    "continueGoogle": "Continuer avec Google",
    "noAccount": "Vous n'avez pas de compte ?",
    "signUp": "S'inscrire",
    "register": "Créer un compte",
    "startTransformation": "Commencez votre transformation avec l'IA.",
    "name": "Nom complet",
    "haveAccount": "Vous avez déjà un compte ?",
    "fillFields": "Veuillez remplir tous les champs",
    "passwordShort": "Le mot de passe doit contenir au moins 8 caractères.",
    "registerFailed": "Échec de l'inscription",
    "forgotPassword": "Mot de passe oublié ?",
    "resetPassword": "Réinitialiser le mot de passe",
    "resetInstructions": "Entrez votre email et nous vous enverrons un lien.",
    "sendLink": "Envoyer le lien",
    "checkEmail": "Vérifiez votre email",
    "linkSent": "Nous avons envoyé un lien de réinitialisation à",
    "returnLogin": "Retour à la connexion"
  },
  pt: {
    "login": "Entrar",
    "welcomeBack": "Bem-vindo de volta!",
    "email": "E-mail",
    "password": "Senha",
    "signIn": "Entrar",
    "creatingAccount": "Criando conta...",
    "continueGoogle": "Continuar com o Google",
    "noAccount": "Não tem uma conta?",
    "signUp": "Inscrever-se",
    "register": "Criar Conta",
    "startTransformation": "Comece sua transformação com IA.",
    "name": "Nome Completo",
    "haveAccount": "Já tem uma conta?",
    "fillFields": "Por favor, preencha todos os campos",
    "passwordShort": "A senha deve ter pelo menos 8 caracteres.",
    "registerFailed": "Falha no registro",
    "forgotPassword": "Esqueceu a senha?",
    "resetPassword": "Redefinir senha",
    "resetInstructions": "Digite seu e-mail e enviaremos um link.",
    "sendLink": "Enviar Link",
    "checkEmail": "Verifique seu e-mail",
    "linkSent": "Enviamos um link de redefinição para",
    "returnLogin": "Voltar ao login"
  },
  it: {
    "login": "Accedi",
    "welcomeBack": "Bentornato!",
    "email": "Email",
    "password": "Password",
    "signIn": "Accedi",
    "creatingAccount": "Creazione account...",
    "continueGoogle": "Continua con Google",
    "noAccount": "Non hai un account?",
    "signUp": "Registrati",
    "register": "Crea Account",
    "startTransformation": "Inizia la tua trasformazione con l'IA.",
    "name": "Nome Completo",
    "haveAccount": "Hai già un account?",
    "fillFields": "Si prega di compilare tutti i campi",
    "passwordShort": "La password deve contenere almeno 8 caratteri.",
    "registerFailed": "Registrazione fallita",
    "forgotPassword": "Password dimenticata?",
    "resetPassword": "Reimposta password",
    "resetInstructions": "Inserisci la tua email e ti invieremo un link.",
    "sendLink": "Invia Link",
    "checkEmail": "Controlla la tua email",
    "linkSent": "Abbiamo inviato un link di ripristino a",
    "returnLogin": "Torna al login"
  },
  de: {
    "login": "Anmelden",
    "welcomeBack": "Willkommen zurück!",
    "email": "E-Mail",
    "password": "Passwort",
    "signIn": "Anmelden",
    "creatingAccount": "Konto wird erstellt...",
    "continueGoogle": "Weiter mit Google",
    "noAccount": "Du hast kein Konto?",
    "signUp": "Registrieren",
    "register": "Konto erstellen",
    "startTransformation": "Beginne deine Transformation mit KI.",
    "name": "Vollständiger Name",
    "haveAccount": "Hast du bereits ein Konto?",
    "fillFields": "Bitte füllen Sie alle Felder aus",
    "passwordShort": "Das Passwort muss mindestens 8 Zeichen lang sein.",
    "registerFailed": "Registrierung fehlgeschlagen",
    "forgotPassword": "Passwort vergessen?",
    "resetPassword": "Passwort zurücksetzen",
    "resetInstructions": "Gib deine E-Mail ein und wir senden dir einen Link.",
    "sendLink": "Link senden",
    "checkEmail": "Überprüfe deine E-Mail",
    "linkSent": "Wir haben einen Zurücksetzungslink gesendet an",
    "returnLogin": "Zurück zur Anmeldung"
  },
  ru: {
    "login": "Войти",
    "welcomeBack": "С возвращением!",
    "email": "Эл. почта",
    "password": "Пароль",
    "signIn": "Войти",
    "creatingAccount": "Создание аккаунта...",
    "continueGoogle": "Продолжить с Google",
    "noAccount": "Нет аккаунта?",
    "signUp": "Зарегистрироваться",
    "register": "Создать аккаунт",
    "startTransformation": "Начните свою трансформацию с ИИ.",
    "name": "Полное имя",
    "haveAccount": "Уже есть аккаунт?",
    "fillFields": "Пожалуйста, заполните все поля",
    "passwordShort": "Пароль должен состоять минимум из 8 символов.",
    "registerFailed": "Ошибка регистрации",
    "forgotPassword": "Забыли пароль?",
    "resetPassword": "Сброс пароля",
    "resetInstructions": "Введите ваш email, и мы отправим вам ссылку.",
    "sendLink": "Отправить ссылку",
    "checkEmail": "Проверьте почту",
    "linkSent": "Мы отправили ссылку для сброса на",
    "returnLogin": "Вернуться ко входу"
  }
};

const onboardingTranslations = {
  fr: {
    "goalTitle": "Quel est votre objectif ?",
    "goalSub": "Nous personnaliserons tout en fonction de cela",
    "loseTitle": "Perdre du Poids",
    "loseSub": "Brûler les graisses, paraître plus mince",
    "stayTitle": "Rester en Bonne Santé",
    "staySub": "Maintenir votre corps actuel",
    "gainTitle": "Prendre du Muscle",
    "gainSub": "Gagner en force et en masse",
    "dietTitle": "Préférences Alimentaires",
    "dietSub": "Sélectionnez ce qui s'applique — optionnel",
    "continue": "Continuer →",
    "letsGo": "C'est parti ! 🚀",
    "back": "← Retour",
    "activitySedentary": "Peu ou pas d'exercice",
    "activityLight": "1–3 jours/semaine",
    "activityModerate": "3–5 jours/semaine",
    "activityActive": "6–7 jours/semaine",
    "activityVeryActive": "Deux fois par jour / sport intense",
    "dietVegetarian": "Végétarien",
    "dietVegan": "Végétalien",
    "dietGlutenFree": "Sans gluten",
    "dietDairyFree": "Sans produits laitiers",
    "dietNutFree": "Sans arachides",
    "dietHalal": "Halal",
    "dietKosher": "Casher",
    "dietKeto": "Céto",
    "statsTitle": "Parlez-nous de vous",
    "statsSub": "Cela nous aide à calculer vos besoins caloriques",
    "sexLabel": "Je suis",
    "activityTitle": "Êtes-vous actif ?",
    "activitySub": "Sélectionnez le niveau qui décrit votre routine hebdomadaire"
  },
  pt: {
    "goalTitle": "Qual é o seu objetivo?",
    "goalSub": "Vamos personalizar tudo em torno disso",
    "loseTitle": "Perder Peso",
    "loseSub": "Queimar gordura, ficar mais magro",
    "stayTitle": "Manter a Forma",
    "staySub": "Manter o corpo atual",
    "gainTitle": "Ganhar Músculo",
    "gainSub": "Ganhar força e massa",
    "dietTitle": "Preferências Alimentares",
    "dietSub": "Selecione o que se aplica — opcional",
    "continue": "Continuar →",
    "letsGo": "Vamos lá! 🚀",
    "back": "← Voltar",
    "activitySedentary": "Pouco ou nenhum exercício",
    "activityLight": "1–3 dias/semana",
    "activityModerate": "3–5 dias/semana",
    "activityActive": "6–7 dias/semana",
    "activityVeryActive": "Duas vezes ao dia / esporte intenso",
    "dietVegetarian": "Vegetariano",
    "dietVegan": "Vegano",
    "dietGlutenFree": "Sem glúten",
    "dietDairyFree": "Sem laticínios",
    "dietNutFree": "Sem nozes",
    "dietHalal": "Halal",
    "dietKosher": "Kosher",
    "dietKeto": "Ceto",
    "statsTitle": "Conte-nos sobre você",
    "statsSub": "Isso nos ajuda a calcular suas necessidades calóricas",
    "sexLabel": "Eu sou",
    "activityTitle": "Quão ativo você é?",
    "activitySub": "Selecione o nível que descreve sua rotina semanal"
  },
  it: {
    "goalTitle": "Qual è il tuo obiettivo?",
    "goalSub": "Personalizzeremo tutto intorno a questo",
    "loseTitle": "Perdere Peso",
    "loseSub": "Bruciare grassi, apparire più magro",
    "stayTitle": "Mantenere la Forma",
    "staySub": "Mantenere il corpo attuale",
    "gainTitle": "Mettere Muscolo",
    "gainSub": "Guadagnare forza e massa",
    "dietTitle": "Preferenze Alimentari",
    "dietSub": "Seleziona ciò che si applica — facoltativo",
    "continue": "Continua →",
    "letsGo": "Andiamo! 🚀",
    "back": "← Indietro",
    "activitySedentary": "Poco o nessun esercizio",
    "activityLight": "1–3 giorni/settimana",
    "activityModerate": "3–5 giorni/settimana",
    "activityActive": "6–7 giorni/settimana",
    "activityVeryActive": "Due volte al giorno / sport intenso",
    "dietVegetarian": "Vegetariano",
    "dietVegan": "Vegano",
    "dietGlutenFree": "Senza glutine",
    "dietDairyFree": "Senza lattosio",
    "dietNutFree": "Senza noci",
    "dietHalal": "Halal",
    "dietKosher": "Kosher",
    "dietKeto": "Keto",
    "statsTitle": "Parlaci di te",
    "statsSub": "Questo ci aiuta a calcolare le tue esigenze caloriche",
    "sexLabel": "Io sono",
    "activityTitle": "Quanto sei attivo?",
    "activitySub": "Seleziona il livello che descrive la tua routine"
  },
  de: {
    "goalTitle": "Was ist dein Hauptziel?",
    "goalSub": "Wir werden alles darauf abstimmen",
    "loseTitle": "Gewicht verlieren",
    "loseSub": "Fett verbrennen, schlanker aussehen",
    "stayTitle": "Gesund bleiben",
    "staySub": "Aktuellen Körper beibehalten",
    "gainTitle": "Muskeln aufbauen",
    "gainSub": "Kraft und Masse aufbauen",
    "dietTitle": "Ernährungspräferenzen",
    "dietSub": "Wähle alles Zutreffende — optional",
    "continue": "Weiter →",
    "letsGo": "Los geht's! 🚀",
    "back": "← Zurück",
    "activitySedentary": "Wenig bis kein Sport",
    "activityLight": "1–3 Tage/Woche",
    "activityModerate": "3–5 Tage/Woche",
    "activityActive": "6–7 Tage/Woche",
    "activityVeryActive": "Zweimal täglich / intensiver Sport",
    "dietVegetarian": "Vegetarisch",
    "dietVegan": "Vegan",
    "dietGlutenFree": "Glutenfrei",
    "dietDairyFree": "Milchfrei",
    "dietNutFree": "Nussfrei",
    "dietHalal": "Halal",
    "dietKosher": "Koscher",
    "dietKeto": "Keto",
    "statsTitle": "Erzähl uns von dir",
    "statsSub": "Das hilft uns, deinen Kalorienbedarf zu berechnen",
    "sexLabel": "Ich bin",
    "activityTitle": "Wie aktiv bist du?",
    "activitySub": "Wähle das Level, das deine Routine beschreibt"
  },
  ru: {
    "goalTitle": "Какова ваша главная цель?",
    "goalSub": "Мы персонализируем все вокруг этого",
    "loseTitle": "Похудеть",
    "loseSub": "Сжечь жир, выглядеть стройнее",
    "stayTitle": "Поддерживать форму",
    "staySub": "Сохранить текущее тело",
    "gainTitle": "Набрать мышцы",
    "gainSub": "Увеличить силу и массу",
    "dietTitle": "Пищевые предпочтения",
    "dietSub": "Выберите подходящее — необязательно",
    "continue": "Продолжить →",
    "letsGo": "Поехали! 🚀",
    "back": "← Назад",
    "activitySedentary": "Мало или нет упражнений",
    "activityLight": "1–3 дня/неделю",
    "activityModerate": "3–5 дней/неделю",
    "activityActive": "6–7 дней/неделю",
    "activityVeryActive": "Дважды в день / интенсивный спорт",
    "dietVegetarian": "Вегетарианец",
    "dietVegan": "Веган",
    "dietGlutenFree": "Без глютена",
    "dietDairyFree": "Без молочных продуктов",
    "dietNutFree": "Без орехов",
    "dietHalal": "Халяль",
    "dietKosher": "Кошер",
    "dietKeto": "Кето",
    "statsTitle": "Расскажите о себе",
    "statsSub": "Это поможет нам рассчитать ваши калории",
    "sexLabel": "Я",
    "activityTitle": "Насколько вы активны?",
    "activitySub": "Выберите уровень вашей активности"
  }
};

for (const lang of langs) {
  const current = JSON.parse(fs.readFileSync('./i18n/translations/' + lang + '.json', 'utf8'));
  
  if (authTranslations[lang]) {
    current.auth = authTranslations[lang];
  }
  if (onboardingTranslations[lang]) {
    current.onboarding = onboardingTranslations[lang];
  }

  fs.writeFileSync('./i18n/translations/' + lang + '.json', JSON.stringify(current, null, 2));
}

console.log('Translated auth and onboarding for all files');
